#!/usr/bin/env python3
"""Recover function boundaries that XenonRecomp's analyzer could not find.

Without a PDB the analyzer falls back to guessing where functions start, and
regularly cuts one real function into several pieces. Whenever translated code
branches to an address outside the piece it lives in, the recompiler cannot
express the branch and emits a `// ERROR <target>` marker followed by a bare
`return` - the function silently does nothing from that point on.

Those markers are exactly the evidence needed to repair the boundaries: a
branch from inside piece A to an address inside piece B proves A and B are
parts of a single function. This scans the generated output for those markers
and emits a TOML `functions = [...]` list that merges each such piece with
everything up to the end of the piece holding its branch target, which can be
fed back into the recompiler.
"""

import argparse
import bisect
import re
from pathlib import Path

FUNC_RE = re.compile(r'^PPC_FUNC_IMPL\(__imp__(?:sub_([0-9A-Fa-f]+)|(\w+))\)')
ERROR_RE = re.compile(r'//\s*ERROR\s+([0-9A-Fa-f]+)')
MAPPING_RE = re.compile(r'\{\s*0x([0-9A-Fa-f]+),')


def load_function_starts(directory: Path) -> list[int]:
    mapping = (directory / "ppc_func_mapping.cpp").read_text()
    return sorted({int(m.group(1), 16) for m in MAPPING_RE.finditer(mapping)})


def collect_broken_ranges(directory: Path, starts: list[int]) -> dict[int, int]:
    """Map function start -> smallest end address that covers its branch targets."""
    needed: dict[int, int] = {}
    for source in sorted(directory.glob("ppc_recomp.*.cpp")):
        current = None
        for line in source.read_text().splitlines():
            function = FUNC_RE.match(line)
            if function:
                current = int(function.group(1), 16) if function.group(1) else None
                continue
            if current is None:
                continue
            error = ERROR_RE.search(line)
            if not error:
                continue
            target = int(error.group(1), 16)
            if target <= current:
                # A backward branch stays inside a merged range that starts at
                # the earlier piece; handled when that piece is processed.
                continue
            # Extend to the end of whichever piece contains the target, so the
            # merged function holds complete instructions rather than half of
            # the target's block.
            index = bisect.bisect_right(starts, target)
            end = starts[index] if index < len(starts) else target + 4
            needed[current] = max(needed.get(current, 0), end)
    return needed


def merge(needed: dict[int, int], starts: list[int]) -> list[tuple[int, int]]:
    merged: list[tuple[int, int]] = []
    for start in sorted(needed):
        end = needed[start]
        if merged and start < merged[-1][1]:
            # This piece is already swallowed by the previous merged function;
            # widen that one instead of emitting an overlapping entry.
            merged[-1] = (merged[-1][0], max(merged[-1][1], end))
            continue
        merged.append((start, end))
    return merged


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("directory", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    starts = load_function_starts(args.directory)
    needed = collect_broken_ranges(args.directory, starts)
    merged = merge(needed, starts)

    with args.output.open("w") as out:
        out.write("# Generated by merge_error_functions.py - function boundaries\n")
        out.write("# recovered from unresolved-branch markers in a previous pass.\n")
        out.write("functions = [\n")
        for start, end in merged:
            out.write("    { address = 0x%08X, size = 0x%X },\n" % (start, end - start))
        out.write("]\n")
    print(f"function starts known: {len(starts)}")
    print(f"pieces with unresolved branches: {len(needed)}")
    print(f"merged function entries written: {len(merged)}")


if __name__ == "__main__":
    main()
